export enum AthleteReadScope {
	PRESCRIBED_BY_TENANT = 'PRESCRIBED_BY_TENANT',
	PRESCRIBED_BY_TENANT_LIFETIME = 'PRESCRIBED_BY_TENANT_LIFETIME',
	TENANT_AND_ATHLETE = 'TENANT_AND_ATHLETE',
	ALL_WORKOUTS = 'ALL_WORKOUTS',
}
